name: Auditoria de Segurança S3

on: [push]

jobs:
  auditoria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Rodar Auditoria
        run: |
          pip install boto3
          python auditor-sec.py

      - name: Salvar Relatório como Artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-auditoria
          path: auditoria-s3.txt
