name: Auditoria de Segurança S3

on: [push]

jobs:
  auditoria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Verificar se Secrets existem
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then echo "ERRO: AWS_ACCESS_KEY_ID não encontrado"; else echo "OK: AWS_ACCESS_KEY_ID detectado"; fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then echo "ERRO: AWS_SECRET_ACCESS_KEY não encontrado"; else echo "OK: AWS_SECRET_ACCESS_KEY detectado"; fi

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Rodar Auditoria
        run: |
          pip install boto3
          python auditor-sec.py
